# Generated by Django 5.2 on 2025-04-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
